apiVersion: v1
kind: Service
metadata:
  name: harness-java-app-service
  namespace: harness-lab
spec:
  selector:
    app: harness-java-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
